import { Building, Campus } from "@/types";

// TODO: 六甲台地区以外にも対応
const campusList: readonly Campus[] = Object.freeze([
    {
        campusId: 3,
        areaName: "六甲台地区",
        campusName: "鶴甲第１キャンパス",
        mapUrl: "/map_turukabuto_1.png",
    },
    {
        campusId: 1,
        areaName: "六甲台地区",
        campusName: "六甲台第１キャンパス",
        mapUrl: "/map_rokkoudai_1.png",
    },
    {
        campusId: 2,
        areaName: "六甲台地区",
        campusName: "六甲台第２キャンパス",
        mapUrl: "/map_rokkoudai_2.png",
    },
    {
        campusId: 4,
        areaName: "六甲台地区",
        campusName: "鶴甲第２キャンパス",
        mapUrl: "/map_turukabuto_2.png",
    },
]);

// TODO: positionX, positionY, pictureUrlを正確な値に変更
// positionについては、ピンの先端の位置が左上から(+16px, -32px)であることを考慮する
const buildingList: readonly Building[] = Object.freeze([
    {
        buildingId: 1,
        campusId: 4,
        buildingName: "体育館",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 2,
        campusId: 4,
        buildingName: "食堂",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 3,
        campusId: 4,
        buildingName: "国際人間科学部、人間発達環境学研究科・G棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 4,
        campusId: 4,
        buildingName: "国際人間科学部、人間発達環境学研究科・D棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 5,
        campusId: 4,
        buildingName:
            "国際人間科学部、人間発達環境学研究科・A棟（人間科学図書館、発達支援インスティテュート）",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 6,
        campusId: 4,
        buildingName: "国際人間科学部、人間発達環境学研究科・E棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 7,
        campusId: 4,
        buildingName: "国際人間科学部、人間発達環境学研究科・B棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 8,
        campusId: 4,
        buildingName: "国際人間科学部、人間発達環境学研究科・F棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 9,
        campusId: 4,
        buildingName: "国際人間科学部、人間発達環境学研究科・C棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 10,
        campusId: 3,
        buildingName: "武道場（養心館）",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 11,
        campusId: 3,
        buildingName: "第二体育館",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 12,
        campusId: 3,
        buildingName: "第一体育館",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 13,
        campusId: 3,
        buildingName:
            "大学教育推進機構（教養教育院）・D棟 （国際コミュニケーションセンター）",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 14,
        campusId: 3,
        buildingName: "大学教育推進機構（教養教育院）・N棟",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 15,
        campusId: 3,
        buildingName: "大学教育推進機構（教養教育院）・K棟",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 16,
        campusId: 3,
        buildingName: "大学教育推進機構（教養教育院）・化学実験室",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 17,
        campusId: 3,
        buildingName:
            "大学教育推進機構（教養教育院、大学教育研究センター）・C棟",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 18,
        campusId: 3,
        buildingName: "国際人間科学部、国際文化学研究科・F棟",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 19,
        campusId: 3,
        buildingName: "大学教育推進機構（教養教育院）・M棟",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 20,
        campusId: 3,
        buildingName:
            "大学教育推進機構（教養教育院）,国際人間科学部,国際文化学研究科・B棟（学生センター）",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 21,
        campusId: 3,
        buildingName: "大学教育推進機構（教養教育院）・大、中講義室",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 22,
        campusId: 3,
        buildingName:
            "国際人間科学部、国際文化学研究科・L棟（キャンパスライフ支援センター）",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 23,
        campusId: 3,
        buildingName: "国際人間科学部、国際文化学研究科・E棟",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 24,
        campusId: 3,
        buildingName:
            "A棟（総合・国際文化学図書館、ラーニングコモンズ、キャリアセンター）",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 25,
        campusId: 3,
        buildingName: "学生会館",
        positionX: 326,
        positionY: 124,
        pictureUrl: "#",
    },
    {
        buildingId: 26,
        campusId: 1,
        buildingName: "人間発達環境学研究科実習観察園、管理棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 27,
        campusId: 1,
        buildingName: "武道場（艱貞堂）",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 28,
        campusId: 1,
        buildingName: "第二研究室",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 29,
        campusId: 1,
        buildingName: "社会科学系フロンティア館（計算社会科学研究センター）",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 30,
        campusId: 1,
        buildingName: "ラ・クール（模擬法廷棟）",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 31,
        campusId: 1,
        buildingName: "第二学舎（法学研究科）",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 32,
        campusId: 1,
        buildingName: "社会科学系図書館",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 33,
        campusId: 1,
        buildingName: "経済経営研究所新館",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 34,
        campusId: 1,
        buildingName: "兼松記念館 （経済経営研究所）",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 35,
        campusId: 1,
        buildingName: "三木記念同窓会館",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 36,
        campusId: 1,
        buildingName: "法科大学院自習棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 37,
        campusId: 1,
        buildingName:
            "本館（経済学研究科、経営学研究科、社会システムイノベーションセンター）",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 38,
        campusId: 1,
        buildingName: "第三学舎",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 39,
        campusId: 1,
        buildingName: "第四学舎（企業資料総合センター）",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 40,
        campusId: 1,
        buildingName: "第五学舎（国際協力研究科）",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 41,
        campusId: 1,
        buildingName: "出光佐三記念六甲台講堂",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 42,
        campusId: 1,
        buildingName: "社会科学系アカデミア館（放送大学兵庫学習センター）",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 43,
        campusId: 2,
        buildingName: "都市安全研究センター(実験棟)",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 44,
        campusId: 2,
        buildingName: "都市安全研究センター(研究棟)",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 45,
        campusId: 2,
        buildingName: "研究基盤センター(機器分析部門)",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 46,
        campusId: 2,
        buildingName: "情報基盤センター(分館)",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 47,
        campusId: 2,
        buildingName: "工学研究科・5E,5W,C4棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 48,
        campusId: 2,
        buildingName: "工学研究科・LR棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 49,
        campusId: 2,
        buildingName: "工学研究科・4E,4W,C3棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 50,
        campusId: 2,
        buildingName: "工学研究科・3E,3W,C2棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 51,
        campusId: 2,
        buildingName: "工学研究科・D1,D2棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 52,
        campusId: 2,
        buildingName: "工学研究科・2E,2W,C1棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 53,
        campusId: 2,
        buildingName: "工学研究科・B棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 54,
        campusId: 2,
        buildingName: "工学研究科・1E,1W棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 55,
        campusId: 2,
        buildingName: "工学研究科・A棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 56,
        campusId: 2,
        buildingName: "工学研究科・環境防災実験室棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 57,
        campusId: 2,
        buildingName: "工学研究科・構造物実験室",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 58,
        campusId: 2,
        buildingName: "工学研究科・建築システム実験室棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 59,
        campusId: 2,
        buildingName: "工学研究科・風洞実験室棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 60,
        campusId: 2,
        buildingName: "工学研究科・音響実験室棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 61,
        campusId: 2,
        buildingName: "工学研究科・音響心理実験室棟",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 62,
        campusId: 2,
        buildingName: "工学研究科・工作技術センター",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 63,
        campusId: 2,
        buildingName: "先端バイオ工学研究センター",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 64,
        campusId: 2,
        buildingName: "先端膜工学研究拠点",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 65,
        campusId: 2,
        buildingName: "自然科学総合研究棟3号館",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 66,
        campusId: 2,
        buildingName: "スカイ ダイニング（工学部食堂）",
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 67,
        buildingName: "工学研究科・工学会館",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 68,
        buildingName: "産官学連携本部",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 69,
        buildingName: "自然科学総合研究棟2号館",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 70,
        buildingName: "自然科学総合研究棟1号館",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 71,
        buildingName: "自然科学総合研究棟4号館",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 72,
        buildingName: "ライフサイエンスラボラトリー",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 73,
        buildingName: "研究基盤センター（アイソトープ部門）",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 74,
        buildingName: "本部（事務局、保健管理センター）",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 75,
        buildingName: "自然科学系図書館",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 76,
        buildingName: "情報基盤センター（本館）",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 77,
        buildingName: "システム情報学研究科（本館）",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 78,
        buildingName: "バイオシグナル総合研究センター棟",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 79,
        buildingName: "理学研究科・C棟",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 80,
        buildingName: "環境保全推進センター",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 81,
        buildingName: "共同実験室",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 82,
        buildingName: "理学研究科・Y,Z棟",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 83,
        buildingName: "理学研究科・B棟",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 84,
        buildingName: "理学研究科・X棟",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 85,
        buildingName: "理学研究科・A棟",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 86,
        buildingName: "研究基盤センター（極低温部門）",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 87,
        buildingName: "農学研究科・農業生産機械工場",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 88,
        buildingName: "農学研究科・畜産加工工場",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 89,
        buildingName: "農学研究科・A棟",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 90,
        buildingName: "農学研究科・B棟",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 91,
        buildingName: "農学研究科・C棟",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 92,
        buildingName: "農学研究科・D棟",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 93,
        buildingName: "農学研究科・E棟",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 94,
        buildingName: "農学研究科・F棟",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 95,
        buildingName: "農学研究科・動物飼育舎",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 96,
        buildingName: "人文学研究科・A棟",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 97,
        buildingName: "人文学研究科・C棟、人文科学図書館",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 98,
        buildingName: "人文学研究科・B棟",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 99,
        buildingName:
            "眺望館（男女共同参画推進室、バリュースクール (V.School)）",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 100,
        buildingName: "瀧川記念学術交流会館",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 101,
        buildingName: "六甲台南食堂LANS BOX（ランスボックス）",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 102,
        buildingName:
            "神戸大学百年記念館（神大会館）、グローバル教育センター、大学文書史料室、誓子・波津女俳句俳諧文庫",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
    {
        buildingId: 103,
        buildingName: "山口誓子記念館",
        campusId: 2,
        positionX: 0,
        positionY: 0,
        pictureUrl: "#",
    },
]);

export { campusList, buildingList };
